### ISSUE TITLE
 Fix deletecodeexample  test

### ISSUE THREAD

**Issue by a22iliru** [HGustavs/LenaSYS#15651]

**Comment by a22iliru** [comment]
I cant fix it because of:
Fatal error: Uncaught PDOException: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ':exampleid)' at line 1 in C:\xampp3\htdocs\LenaSYS\Shared\test.php:88 Stack trace: #0 C:\xampp3\htdocs\LenaSYS\Shared\test.php(88): PDOStatement->execute() #1 C:\xampp3\htdocs\LenaSYS\Shared\test.php(179): doDBQuery(Object(PDOStatement), 'UNK', 'UNK', 'UNK') #2 C:\xampp3\htdocs\LenaSYS\DuggaSys\tests\microservices\codeviewerService\deleteCodeExample_ms_test.php(34): testHandler(Array, true) #3 {main} thrown in C:\xampp3\htdocs\LenaSYS\Shared\test.php on line 88

Will be moving on to another issue
